-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://oathkeeper.localhost:9000/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    -
      handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:kssui:anonymous"
  upstream:
    preserve_host: true
    url: "http://kssui:3000"
  match:
    url: "http://oathkeeper.localhost:9000/<{registration,welcome,recovery,verification,login,error,**.css,**.js,**.png,}>"
    methods:
      - GET
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:kssui:protected"
  upstream:
    preserve_host: true
    url: "http://kssui:3000"
  match:
    url: "http://oathkeeper.localhost:9000/<{debug,dashboard,settings}>"
    methods:
      - GET
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://kssui.localhost:9000/login