-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
  match:
    url: "https://kratos.ory.localhost/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:ui:anon"
  upstream:
    preserve_host: true
    url: "http://ui:3000"
  match:
    url: "http://ui.ory.localhost:9000/<{registration*,welcome,recovery*,verification*,login*,error,**.css,**.js,**.png,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:ui:protected"
  upstream:
    preserve_host: true
    url: "http://ui:3000"
  match:
    url: "http://ui.ory.localhost:9000/<{debug*,dashboard,settings*}>"
    methods:
      - GET
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://ui.ory.localhost:9000/login


-
  id: "ory:ui-https:anonymous"
  upstream:
    preserve_host: true
    url: "http://ui:3000"
  match:
    url: "https://ui.ory.localhost/<{registration*,welcome,recovery*,verification*,login*,error,**.css,**.js,**.png,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:ui-https:protected"
  upstream:
    preserve_host: true
    url: "http://ui:3000"
  match:
    url: "https://ui.ory.localhost/<{debug*,dashboard,settings*}>"
    methods:
      - GET
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: https://ui.ory.localhost/login

-
  id: "ory:whoami-https:protected"
  upstream:
    preserve_host: true
    url: "http://whoami:80"
  match:
    url: "https://whoami.ory.localhost/<**>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
    - handler: header
      config:
        headers:
          X-Id: '{{ print .Subject }}'
          X-Email: '{{ print .Extra.identity.traits.email }}'
  errors:
    - handler: redirect
      config:
        to: https://ui.ory.localhost/login