version: v0.7.0-alpha.1

log:
  level: debug

namespaces:
  - name: organization
    id: 1
  - name: pro_org
    id: 2
  - name: platform
    id: 3
  - name: enterprise_org
    id: 4


serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467